[package]
authors = ["Tobychev <tobychev@live.com>"]
name = "personregister"
version = "0.1.0"

[dependencies]
rocket = "0.2.9"
rocket_codegen = "0.2.9"
serde = "0.9"
serde_derive = "0.9"
serde_json = "1.0.2"
uuid = { version = "0.4.0", features = ["serde"]}

[dependencies.diesel]
version = "0.13.0"
features = ["mysql"]

[dependencies.diesel_codegen]
version = "0.13.0"
features = ["mysql"]

[dependencies.rocket_contrib]
version = "0.2.9"
default-features = false
features = ["json","uuid"]
